var FlatListData =[
    {
        id:1,
        name:"Caffe Latte",
        piece:2,
        price:30,
       // image:require("./images/image2.jpg"),
    },
    {
        id:2,
        name:"Caffe ",
        piece:3,
        price:45,
       // image:require("./images/image2.jpg"),
    },
    {
        id:3,
        name:"Cjj",
        piece:4,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:4,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:5,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:6,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:7,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:8,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:9,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:10,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:11,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:12,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:13,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:14,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:15,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:16,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:17,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },{
        id:18,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    {
        id:19,
        name:"Cjj",
        piece:5,
        price:50,
       // image:require("./images/image2.jpg"),
    },
    ];
    
    module.exports=FlatListData;