var FlatListData =[
{
    id:1,
    name:"Caffe Latte",
    adress:"Nişantaşı Mahallesi",
    minutes:15,
    price:30,
   // image:require("./images/image2.jpg"),
},
{
    id:2,
    name:"Caffe Latte",
    adress:"Nişantaşı Mahallesi",
    minutes:15,
    price:45,
   // image:require("./images/image2.jpg"),
},
{
    id:3,
    name:"Caffe Latte",
    adress:"Nişantaşı Mahallesi",
    minutes:15,
    price:50,
   // image:require("./images/image2.jpg"),
},
{
    id:4,
    name:"Caffe Latte",
    adress:"Nişantaşı Mahallesi",
    minutes:15,
    price:50,
   // image:require("./images/image2.jpg"),
},
{
    id:5,
    name:"Caffe Latte",
    adress:"Nişantaşı Mahallesi",
    minutes:15,
    price:50,
   // image:require("./images/image2.jpg"),
},
{
    id:6,
    name:"Caffe Latte",
    adress:"Nişantaşı Mahallesi",
    minutes:15,
    price:50,
   // image:require("./images/image2.jpg"),
},
{
    id:7,
    name:"Caffe Latte",
    adress:"Nişantaşı Mahallesi",
    minutes:15,
    price:50,
   // image:require("./images/image2.jpg"),
},
{
    id:8,
    name:"Caffe Latte",
    adress:"Nişantaşı Mahallesi",
    minutes:15,
    price:50,
   // image:require("./images/image2.jpg"),
},
{
    id:9,
    name:"Caffe Latte",
    adress:"Nişantaşı Mahallesi",
    minutes:15,
    price:50,
   // image:require("./images/image2.jpg"),
},
{
    id:10,
    name:"Caffe Latte",
    adress:"Nişantaşı Mahallesi",
    minutes:15,
    price:50,
   // image:require("./images/image2.jpg"),
},

];

module.exports=FlatListData;